#change profiles
spring:
  profiles:
    active: dev
  
  #资源文件定位  
  messages:
    basename: i18n/messages
  
  #freemarker配置
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    prefix: 
    suffix: .ftl
    #如果需要使用国际化，导入spring.ftl，此处需要打开spring微服务
    expose-spring-macro-helpers: true
    settings:
      auto_import: /spring.ftl as spring   #导入页面spring标签

  #启用redis配置
  cache:
    type: redis
    redis:
      time-to-live: 60000  #缓存有效期 
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:  
  
#mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  
